### ISSUE TITLE
events not updated

### ISSUE THREAD

**Issue by paul-shibanov** [paradox41/angular-chartist.js#100]
events are [$watched](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L27) but they don't updated when [chart is rendered](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L67)

**Comment by paradox41** [comment]
The function you are pointing to is not the rendering function, that is the update function which is part of Chartist itself. Are new events not being correctly add when the chart gets updated?

**Comment by paul-shibanov** [comment]
No, I'm pointing that when chart is rendered, [bindEvents](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L38-L42) are not called on events object change.

**Comment by paul-shibanov** [comment]
I.e new events not getting executed at all, always executed initial ones

**Comment by paradox41** [comment]
If the chart need to be completely re-rendered [(because for example the chart type changes)](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L64-L65) then [the events do get rebound](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L49). Otherwise, the chart simply gets updated.

So this is supposed to fix the case where the chart is simply getting updated, correct?

**Comment by paul-shibanov** [comment]
Yes, when you simply update the events, for example you highlight 
```js
draw: function(context) {
  if (context.type === 'point') {
  //logic
  }
```
when this updates 
```js
draw: function(context) {
  if (context.type === 'point') {
  //new logic
  }
```
correct one will be executed [on update](https://github.com/paradox41/angular-chartist.js/blob/master/src/angular-chartist.js#L67)

**Comment by paul-shibanov** [comment]
also now I'm thinking about the case when chart type gets updated. old events are not unbinded.

**Comment by paul-shibanov** [comment]
No, I checked. They're destroyed
