### ISSUE TITLE
Consider changing name of package to angular-chartist

### ISSUE THREAD

**Issue by amangupta052** [paradox41/angular-chartist.js#56]
I ran into small issue when running this against grunt build. The default config of many build tools to is to take files ending with ".js" and do something with them. Since this is a directory, I got a EISDIR issue with it. 

I had to finally add an exception for angular-chartist.js . Would have been easier if it was named conventionally.

**Comment by paradox41** [comment]
Hey there, sorry to hear you had an issue with naming. 

I'll have to think about this, just looking at some of the top [JavaScript packages](https://github.com/search?l=JavaScript&o=desc&q=js&ref=searchresults&s=stars&type=Repositories&utf8=%E2%9C%93) I see that there are actually a few that have a period in the name, so I don't think it is fair to say that this particular package is named unconventionally. 

With that said, I will think about this. If more people come in and say they are having issues, then I think that will be sufficient to change my mind. Otherwise, you are the first that has come to me with such an issue.

**Comment by amangupta052** [comment]
Sure, thanks for the quick reply!

Just for future reference, I was using the default Gruntfile that comes with [angular-fullstack](https://github.com/DaftMonk/generator-angular-fullstack). I ran into this issue in the 'usemin' task, where it looks for all `.js` files to minify and send downstream.

**Comment by paradox41** [comment]
Not a problem. Like I said, not totally opposed, but I don't think there is sufficient reason to do so.

Also, FWIW, I would honestly say this is a bug on the side of the grunt plugin. I feel like it is a bit of a naive implementation to assume that anything ending in `.js` is a file. Just my two cents.
